// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAnrdknUVRAtG4fZaJ6S500A2pn-wCmFI',
    appId: '1:81310175675:web:a193ff01d900b98330749e',
    messagingSenderId: '81310175675',
    projectId: 'todofirebase-7cf60',
    authDomain: 'todofirebase-7cf60.firebaseapp.com',
    storageBucket: 'todofirebase-7cf60.appspot.com',
    measurementId: 'G-HV7BD8G4CN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkJmKELl_WXr0zY8IkzKPUOqghabzYMfE',
    appId: '1:81310175675:android:0f5268cce1d2a9fe30749e',
    messagingSenderId: '81310175675',
    projectId: 'todofirebase-7cf60',
    storageBucket: 'todofirebase-7cf60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrwgrbDte0msV9CKDcohz_80dS_-b5zi4',
    appId: '1:81310175675:ios:c5b3585575c1aa5f30749e',
    messagingSenderId: '81310175675',
    projectId: 'todofirebase-7cf60',
    storageBucket: 'todofirebase-7cf60.appspot.com',
    iosBundleId: 'com.example.firebaseDisplay',
  );
}
